#!/usr/bin/env node
/**
 * tools/encrypt-links.js
 *
 * Encrypts data/links.json with a password and writes data/links_encrypted.js.
 * The output file is safe to commit to a public repo — only someone who knows
 * the password can decrypt the bookmarks.
 *
 * Usage:
 *   node tools/encrypt-links.js
 *   node tools/encrypt-links.js --password "mypassword"
 *   node tools/encrypt-links.js --input path/to/custom.json
 *
 * Then enable password protection in script.js:
 *   ENCRYPT_DATA: true
 *
 * NOTE: Security model
 *   This protects your bookmarks from casual discovery. The encryption uses
 *   AES-256-GCM with a PBKDF2-derived key, so the ciphertext is secure as long
 *   as your password is strong. A determined attacker with the encrypted file
 *   could attempt an offline brute-force, so prefer a long passphrase.
 */
'use strict';

const fs       = require('fs');
const path     = require('path');
const crypto   = require('crypto');
const readline = require('readline');

const PBKDF2_ITERATIONS = 100_000; // must match script.js
const ROOT = path.resolve(__dirname, '..');

function getArg(flag) {
  const idx = process.argv.indexOf(flag);
  return idx !== -1 && idx + 1 < process.argv.length ? process.argv[idx + 1] : null;
}

function promptPassword() {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input:  process.stdin,
      output: process.stdout,
    });
    // Hide password input when the terminal supports it.
    if (process.stdin.isTTY) {
      process.stdout.write('Enter password: ');
      process.stdin.setRawMode(true);
      let pwd = '';
      process.stdin.resume();
      process.stdin.setEncoding('utf8');
      process.stdin.on('data', (ch) => {
        if (ch === '\n' || ch === '\r' || ch === '\u0003') {
          process.stdin.setRawMode(false);
          process.stdout.write('\n');
          rl.close();
          resolve(pwd);
        } else if (ch === '\u007F') {
          pwd = pwd.slice(0, -1);
        } else {
          pwd += ch;
        }
      });
    } else {
      rl.question('Enter password: ', (answer) => {
        rl.close();
        resolve(answer);
      });
    }
  });
}

async function main() {
  const inputPath  = getArg('--input')    || path.join(ROOT, 'data', 'links.json');
  const outputPath = getArg('--output')   || path.join(ROOT, 'data', 'links_encrypted.js');
  const password   = getArg('--password') || await promptPassword();

  if (!password) {
    console.error('Error: password cannot be empty.');
    process.exit(1);
  }

  if (!fs.existsSync(inputPath)) {
    console.error(`Error: input file not found: ${inputPath}`);
    console.error('       Create data/links.json first (see README).');
    process.exit(1);
  }

  const plaintext = Buffer.from(fs.readFileSync(inputPath, 'utf8'), 'utf8');

  // Random salt (16 bytes) and IV (12 bytes — recommended for AES-GCM).
  const salt = crypto.randomBytes(16);
  const iv   = crypto.randomBytes(12);

  // Derive a 256-bit key from the password using PBKDF2-SHA256.
  const keyBytes = crypto.pbkdf2Sync(password, salt, PBKDF2_ITERATIONS, 32, 'sha256');

  // Encrypt with AES-256-GCM.
  const cipher    = crypto.createCipheriv('aes-256-gcm', keyBytes, iv);
  const encrypted = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  const authTag   = cipher.getAuthTag(); // 16 bytes

  // Web Crypto API's AES-GCM expects the 16-byte auth tag appended to the ciphertext.
  const ciphertext = Buffer.concat([encrypted, authTag]);

  const payload = {
    salt:       salt.toString('base64'),
    iv:         iv.toString('base64'),
    ciphertext: ciphertext.toString('base64'),
  };

  const output = [
    '// Encrypted links — generated by tools/encrypt-links.js',
    '// Safe to commit: the password is required to decrypt the bookmarks.',
    '// Regenerate whenever you update data/links.json:',
    '//   node tools/encrypt-links.js',
    'window.ENCRYPTED_LINKS = ' + JSON.stringify(payload, null, 2) + ';',
    '',
  ].join('\n');

  fs.writeFileSync(outputPath, output, 'utf8');

  const rel = (p) => path.relative(process.cwd(), p);
  console.log(`✓  ${rel(inputPath)}  →  ${rel(outputPath)}`);
  console.log(`   To enable the password gate, set  ENCRYPT_DATA: true  in script.js CONFIG.`);
}

main().catch((err) => {
  console.error('Fatal:', err.message);
  process.exit(1);
});
